[package]
name = "librelink"
version = "0.1.0"
edition = "2021"
authors = ["Nathael Bonnal <pro.nathaelbonnal@gmail.com>"] 


[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = "1.38.0"


